apiVersion: v1
data:
  OAUTH_CLIENT_ID: c3J2Yy1hY2N0LTc1MGQ3OTg2LTlmNzktNDhmNy1hZTY2LTIxYjUxMDY3MTZhOQ==
  OAUTH_CLIENT_SECRET: NGQ0NDVkNjktZWQwMS00YzVmLWI0YmItY2MyNzE3ZTA5ZDE1
kind: Secret
metadata:
  creationTimestamp: "2021-11-08T10:45:49Z"
  name: camel-quarkus-kafka-mcs-secret
  namespace: default
  resourceVersion: "577"
  uid: dd82a389-321c-462a-8320-2e31b8bb863b
type: Opaque
